# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Human < Formula
  desc "Issue tracker CLI for AIs"
  homepage "https://github.com/StephanSchmidt/human"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/StephanSchmidt/human/releases/download/v0.6.0/human_0.6.0_darwin_amd64.tar.gz"
      sha256 "44d2c5cda4730496d39b2b1775411b44c891c68dcd9e11c120cbd1d49ae6b4c1"

      define_method(:install) do
        bin.install "human"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/StephanSchmidt/human/releases/download/v0.6.0/human_0.6.0_darwin_arm64.tar.gz"
      sha256 "393dacc003be96e1ecaccbf336bf1888f8d020e22304406e46b7719174bb3679"

      define_method(:install) do
        bin.install "human"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/StephanSchmidt/human/releases/download/v0.6.0/human_0.6.0_linux_amd64.tar.gz"
      sha256 "9c5645ecbccc8bf92a196e45b1868589045228849e2b99cc5a8256a44545781f"
      define_method(:install) do
        bin.install "human"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/StephanSchmidt/human/releases/download/v0.6.0/human_0.6.0_linux_arm64.tar.gz"
      sha256 "6523e2dde7334b280a243be2f5e6a5413184ee3172536ce6c10d5d54c87fee92"
      define_method(:install) do
        bin.install "human"
      end
    end
  end
end
