# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Loupe < Formula
  desc "Diagnostic CLI that measures the impact of AI coding assistants on engineering teams"
  homepage "https://github.com/StephanSchmidt/loupe"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/StephanSchmidt/loupe/releases/download/v0.3.0/loupe_0.3.0_darwin_amd64.tar.gz"
      sha256 "19d9ce23e3fcaa062fbc36b111c41529143c511fbf1e571ff959a5fece06bfd7"

      define_method(:install) do
        bin.install "loupe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/StephanSchmidt/loupe/releases/download/v0.3.0/loupe_0.3.0_darwin_arm64.tar.gz"
      sha256 "efd12ffe80542b311e77e59867ecc5bc90dc508e65906aa2ae8c37f0b9e74465"

      define_method(:install) do
        bin.install "loupe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/StephanSchmidt/loupe/releases/download/v0.3.0/loupe_0.3.0_linux_amd64.tar.gz"
      sha256 "f3db2c662e546fe9a3d29bd099dbd319e89cfe3a73b0bed3d766cd4067be7503"
      define_method(:install) do
        bin.install "loupe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/StephanSchmidt/loupe/releases/download/v0.3.0/loupe_0.3.0_linux_arm64.tar.gz"
      sha256 "c42f1ba1774234f7a69624d04c8bef97dcb2843b5e5d5e1c014b681dd12947ce"
      define_method(:install) do
        bin.install "loupe"
      end
    end
  end

  test do
    system "#{bin}/loupe", "--version"
  end
end
