# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Loupe < Formula
  desc "Diagnostic CLI that measures the impact of AI coding assistants on engineering teams"
  homepage "https://github.com/StephanSchmidt/loupe"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/StephanSchmidt/loupe/releases/download/v0.1.0/loupe_0.1.0_darwin_amd64.tar.gz"
      sha256 "f6eae887fbf8dfb6fe1d9304b34a124ff3ee3bb81760c643d0d7ff30ce1a5596"

      define_method(:install) do
        bin.install "loupe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/StephanSchmidt/loupe/releases/download/v0.1.0/loupe_0.1.0_darwin_arm64.tar.gz"
      sha256 "bf6a5e7bdf0e706bf3e7699faddbe2d0172e28704a9966dd15f0010b3445b51a"

      define_method(:install) do
        bin.install "loupe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/StephanSchmidt/loupe/releases/download/v0.1.0/loupe_0.1.0_linux_amd64.tar.gz"
      sha256 "b4d6645bddd06b1149fad7312f5b48ae9c63acfd81b3ba270dd92dd92a52ef43"
      define_method(:install) do
        bin.install "loupe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/StephanSchmidt/loupe/releases/download/v0.1.0/loupe_0.1.0_linux_arm64.tar.gz"
      sha256 "a49a7e63a6397966ae64f0fa4b8ad057f87d3d0599ffee11cb517e7c68ed0c89"
      define_method(:install) do
        bin.install "loupe"
      end
    end
  end

  test do
    system "#{bin}/loupe", "--version"
  end
end
